// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmkCdqDEy7R_wKW_3A9g7FxiksVudpt08',
    appId: '1:340504802217:web:f534320c592ba78cda4ab8',
    messagingSenderId: '340504802217',
    projectId: 'shopify-app-c52b4',
    authDomain: 'shopify-app-c52b4.firebaseapp.com',
    storageBucket: 'shopify-app-c52b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS66KspNTte3LNMKXDn69y7xfJT06PXWA',
    appId: '1:340504802217:android:4399bf7d5ed1f6b6da4ab8',
    messagingSenderId: '340504802217',
    projectId: 'shopify-app-c52b4',
    storageBucket: 'shopify-app-c52b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgw69yfOXWM-6CTEjvbzuzykWeNLzFgKA',
    appId: '1:340504802217:ios:bc7c0351e3d0fd88da4ab8',
    messagingSenderId: '340504802217',
    projectId: 'shopify-app-c52b4',
    storageBucket: 'shopify-app-c52b4.appspot.com',
    iosBundleId: 'com.example.shopifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgw69yfOXWM-6CTEjvbzuzykWeNLzFgKA',
    appId: '1:340504802217:ios:3d31e999f5c5f7e1da4ab8',
    messagingSenderId: '340504802217',
    projectId: 'shopify-app-c52b4',
    storageBucket: 'shopify-app-c52b4.appspot.com',
    iosBundleId: 'com.example.shopifyApp.RunnerTests',
  );
}
